name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: check env
      run: echo $DATABASE_URL
    - name: check cache
      run: ls
    - name: Build
      run: cargo build
      env: 
        SQLX_OFFLINE: true
