name: Shuttle Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@main
        env: 
          SQLX_OFFLINE: true
        with:
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
          secrets: |
            JWT_SECRET = '${{ secrets.JWT_SECRET }}'
            SALT_PHRASE = '${{ secrets.SALT_PHRASE }}'
